# Generated by Django 3.2.9 on 2022-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0038_auto_20220324_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutstorage',
            name='operateday',
            field=models.DateTimeField(auto_now=True, verbose_name='操作日期'),
        ),
    ]
