# Generated by Django 3.2.9 on 2022-04-21 16:31

import Service.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_auto_20220321_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('batchno', models.CharField(default='', max_length=6, validators=[Service.models.validate_length], verbose_name='编号')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '编号生成器',
                'ordering': ('-created',),
            },
        ),
    ]
