# Generated by Django 3.2.9 on 2022-04-23 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_auto_20220423_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchno',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
