# Generated by Django 3.2.9 on 2022-04-26 16:03

import Service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_auto_20220423_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchno',
            name='batchno',
            field=models.CharField(default='', max_length=5, validators=[Service.models.validate_length], verbose_name='编号'),
        ),
    ]
