# Generated by Django 3.2.9 on 2022-04-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0032_auto_20220417_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processassemble',
            options={'ordering': ('-updated',), 'verbose_name_plural': '装配中'},
        ),
        migrations.AlterModelOptions(
            name='processmeprepare',
            options={'ordering': ('-updated',), 'verbose_name_plural': '机械件准备'},
        ),
        migrations.AlterModelOptions(
            name='processscprepare',
            options={'ordering': ('-updated',), 'verbose_name_plural': '干涉仪准备'},
        ),
        migrations.AlterModelOptions(
            name='processtesting',
            options={'ordering': ('-updated',), 'verbose_name_plural': '测试中'},
        ),
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ('-updated',), 'verbose_name_plural': '订单历史'},
        ),
        migrations.AlterModelOptions(
            name='productplan',
            options={'ordering': ('-updated',), 'verbose_name_plural': '订单管理'},
        ),
    ]
