# Generated by Django 3.2.9 on 2022-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0035_auto_20220524_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplan',
            name='productid',
            field=models.CharField(max_length=20, verbose_name='产品型号'),
        ),
        migrations.AlterField(
            model_name='productplan',
            name='serial',
            field=models.CharField(max_length=20, verbose_name='序列号'),
        ),
    ]
