# Generated by Django 3.2.9 on 2022-06-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productplan', '0036_auto_20220525_0948'),
        ('productplan', '0036_auto_20220616_1109'),
    ]

    operations = [
    ]
